CREATE TABLE IF NOT EXISTS Chief (
chief_id SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Employee (
employee_id SERIAL PRIMARY KEY,
name VARCHAR(155) NOT NULL,
department VARCHAR(205) NOT NULL,
chief INTEGER NOT NULL REFERENCES Chief(chief_id),
is_the_boss BOOLEAN NOT NULL
);